#! /bin/bash
#
# Copyright (c) 2017-8 NVIDIA Corporation
# Reply-To: Bryce Adelstein Lelbach aka wash <brycelelbach@gmail.com>
#
# Distributed under the Boost Software License v1.0 (boost.org/LICENSE_1_0.txt)

if [[ $# -ne 1 ]]; then
  echo "Usage: $0 <changelist>"
  echo 
  echo "Print the tab-indented description of the specified Perforce changelist "
  echo "without a terminating newline."
  exit 1
fi

p4 describe -s $1 | sed '1,2d' | tr '\n' '\r' | sed 's/\r\r/\f/' | sed 's/\([^\f]*\)\f.*/\1/' | tr '\r' '\n' | tr '\f' '\n'

