#! /usr/bin/env bash
#
# Copyright (c) 2017-2020 NVIDIA Corporation
# Reply-To: Bryce Adelstein Lelbach aka wash <brycelelbach@gmail.com>
#
# Distributed under the Boost Software License v1.0 (boost.org/LICENSE_1_0.txt)

if [[ ${#} -eq 0 ]]; then
  echo "Usage: ${0} <changelist...>"
  echo
  echo "Delete the specified changelist(s), including shelves if they exist."
  exit 1
fi

for cl in ${@}
do
  p4 shelve -d -c ${cl} > /dev/null 2>&1
  p4 change -d ${cl}
done

