#! /bin/bash
#
# Copyright (c) 2017-8 NVIDIA Corporation
# Reply-To: Bryce Adelstein Lelbach aka wash <brycelelbach@gmail.com>
#
# Distributed under the Boost Software License v1.0 (boost.org/LICENSE_1_0.txt)

function usage {
  echo "Usage: $0 [flags...] <changelist>"
  echo
  echo "-h, -help, --help : Print this message."
  echo "-n                : Do not output a terminating newline."
  echo
  echo "Print the tab-indented description of the specified Perforce changelist."
  exit 1
}
  
TERMINATING_NEWLINE=1

while test ${#} != 0
do
  case "${1}" in
  -h) usage ;;
  -help) usage ;;
  --help) usage ;;
  -n) TERMINATING_NEWLINE=0 ;;
  *)
    # If CHANGELIST is already set, then we've gotten more than one positional
    # argument, which is wrong.
    if [ -n "${CHANGELIST}" ]
    then
      usage
    fi
    CHANGELIST="${1}"
    ;;
  esac
  shift
done

p4 describe -s ${CHANGELIST} | sed '1,2d' | tr '\n' '\r' | sed 's/\r\r/\f/' | sed 's/\([^\f]*\)\f.*/\1/' | tr '\r' '\n' | tr '\f' '\n'

if [ "${TERMINATING_NEWLINE:-0}" == "1" ]
then
  echo
fi

