#! /usr/bin/env bash
#
# Copyright (c) 2017-2020 NVIDIA Corporation
# Reply-To: Bryce Adelstein Lelbach aka wash <brycelelbach@gmail.com>
#
# Distributed under the Boost Software License v1.0 (boost.org/LICENSE_1_0.txt)

if [[ $# -ne 1 ]]; then
  echo "Usage: $0 <changelist>"
  echo
  echo "Delete the specified changelist, including its shelve if it exists."
  exit 1
fi

p4 shelve -d -c $1 > /dev/null 2>&1
p4 change -d $1

