#! /usr/bin/env bash
#
# Copyright (c) 2017-2020 NVIDIA Corporation
# Reply-To: Bryce Adelstein Lelbach aka wash <brycelelbach@gmail.com>
#
# Distributed under the Boost Software License v1.0 (boost.org/LICENSE_1_0.txt)

if [[ $# -eq 0 ]]; then
  echo "Usage: $0 <args...>"
  echo
  echo "Invoke the Perforce command \`p4 describe\` with the diff style set to "
  echo "unified."
  exit 1
fi

p4 describe -du $@

