#! /usr/bin/env bash
#
# Copyright (c) 2017-2020 NVIDIA Corporation
# Reply-To: Bryce Adelstein Lelbach aka wash <brycelelbach@gmail.com>
#
# Distributed under the Boost Software License v1.0 (boost.org/LICENSE_1_0.txt)

if [[ $# -ne 3 ]]; then
  echo "Usage: $0 <changelist> <from-path> <to-path>"
  echo
  echo "Create a new changelist that integrate (aka copy) the changes in the "
  echo "specified changelist from one Perforce path to another Perforce path. "
  echo "The new changelist will have the same description as the source "
  echo "changelist, with an added note explaining where the change was "
  echo "integrated from. The path arguments should be paths in the Perforce "
  echo "repository, not paths in your local workspace."
  exit 1
fi

CHANGELIST=${1}
FROM_PATH=${2%/}
TO_PATH=${3%/}

# Integrate the changelist.
FILES=`p4 integrate ${FROM_PATH}/...@=${CHANGELIST} ${TO_PATH}/... | sed 's/#.*$//'`

# Sync the location we integrated to.
p4 sync ${TO_PATH}/...

# Resolve anything that has no conflicts automatically.
p4 resolve -am ${TO_PATH}/...
# Prompt the user to resolve anything with conflicts.
p4 resolve ${TO_PATH}/...

# Create the integration changelist, using the description of the original CL
# with the description supplied on the command line appended.
INTEGRATION_CHANGELIST=`(cat - | p4 change -i) << EOF
Change: new

Status: new

Description:
$(p4-description -n ${CHANGELIST})

	Integrates ${FROM_PATH}/...@=${CHANGELIST} to ${TO_PATH}/...

Files:
$(echo "${FILES}" | sed 's/^/\t/')
EOF
`

# Extract the integration changelist number.
INTEGRATION_CHANGELIST=`echo "${INTEGRATION_CHANGELIST}" | awk -F ' ' '{ print $2 }'`

# Shelve the CL and revert it.
p4 shelve -c ${INTEGRATION_CHANGELIST}
p4 revert -w -c ${INTEGRATION_CHANGELIST} //...

echo "Created changelist ${INTEGRATION_CHANGELIST} that integrates ${CHANGELIST} from ${FROM_PATH}/... to ${TO_PATH}/..."

