#! /bin/bash
#
# Copyright 2017 NVIDIA Corporation
#
# Distributed under the Boost Software License v1.0 (boost.org/LICENSE_1_0.txt)
#
# Author: Bryce Adelstein Lelbach aka wash <brycelelbach@gmail.com>

if [[ $# -ne 3 ]]; then
  echo "Usage: $0 <changelist> <from-path> <to-path>"
  exit 1
fi

CHANGELIST=${1}
FROM_PATH=${2%/}
TO_PATH=${3%/}

# Integrate the changelist.
FILES=`p4 integrate ${FROM_PATH}/...@=${CHANGELIST} ${TO_PATH}/... | sed 's/#.*$//'`

# Sync the location we integrated to.
p4 sync ${TO_PATH}/...

# Resolve any conflicts in the location we integrated to.
p4 resolve ${TO_PATH}/...

# Create the integration changelist, using the description of the original CL
# with the description supplied on the command line appended.
INTEGRATION_CHANGELIST=`(cat - | p4 change -i) << EOF
Change: new

Status: new

Description:
$(p4-description ${CHANGELIST})
	Integrates ${FROM_PATH}/...@=${CHANGELIST} to ${TO_PATH}/...

Files:
$(echo "${FILES}" | sed 's/^/\t/')
EOF
`

# Extract the integration changelist number.
INTEGRATION_CHANGELIST=`echo "${INTEGRATION_CHANGELIST}" | awk -F ' ' '{ print $2 }'`

# Shelve the CL and revert it.
p4 shelve -c ${INTEGRATION_CHANGELIST}
p4 revert -w -c ${INTEGRATION_CHANGELIST} //...

echo "Created changelist ${INTEGRATION_CHANGELIST} that integrates ${CHANGELIST} from ${FROM_PATH}/... to ${TO_PATH}/..."

