#! /usr/bin/env bash
#
# Copyright (c) 2017-2020 NVIDIA Corporation
# Reply-To: Bryce Adelstein Lelbach aka wash <brycelelbach@gmail.com>
#
# Distributed under the Boost Software License v1.0 (boost.org/LICENSE_1_0.txt)

if [[ $# -ne 1 ]]; then
  echo "Usage: $0 <changelist>"
  echo
  echo "Print a scriptable list of the local paths of the files in the specified "
  echo "Perforce changelist."
  exit 1
fi

p4 describe -s $1 | grep '... //' | sed 's/\.\.\. //' | sed 's/#.*$//' | p4 -ztag -x - where | grep '... path ' | sed 's/\.\.\. path //'

