#! /bin/bash
#
# Copyright (c) 2017-8 NVIDIA Corporation
# Reply-To: Bryce Adelstein Lelbach aka wash <brycelelbach@gmail.com>
#
# Distributed under the Boost Software License v1.0 (boost.org/LICENSE_1_0.txt)

if [[ $# -ne 1 ]]; then
  echo "Usage: $0 <changelist>"
  echo 
  echo "Submit (aka commit) the specified **shelved** Perforce changelist."
  echo "You will have the opportunity to edit the changelist description before "
  echo "it is submitted."
  exit 1
fi

CHANGELIST=${1}

p4 unshelve -s ${CHANGELIST} -c ${CHANGELIST}
p4 change ${CHANGELIST} # Allow the user a chance to update the description.
p4 shelve -d -c ${CHANGELIST}
p4 submit -c ${CHANGELIST}

