#! /usr/bin/env bash
#
# Copyright (c) 2017-8 NVIDIA Corporation
# Reply-To: Bryce Adelstein Lelbach aka wash <brycelelbach@gmail.com>
#
# Distributed under the Boost Software License v1.0 (boost.org/LICENSE_1_0.txt)

if [[ $# -ne 1 ]]; then
  echo "Usage: $0 <changleist>"
  echo
  echo "Unshelve a changelist."
  exit 1
fi

p4 unshelve -c $1 -s $1

